# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7db1e1f8708ad2bea3e5c7daf4ea795c0cb9174f8d3b369a58bba29883ec8517edaa0e7679d04052dcad39b4d8538914c5e45fca6c103e4b43ff8414a8824b32

test:
  secret_key_base: d9ad3c03df2ad192cc8bcc261d9211231d849e79a6de7a341d4514fd86060ed3c2424833d748ba64496668567e3f65f23b08bfa4967b12002c7e4d90a3a5e7f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
